train: "/media/rmedu-4090/New Volume1/samin-workforceRTX/license_plate_detector/data/train/images"
val: "/media/rmedu-4090/New Volume1/samin-workforceRTX/license_plate_detector/data/valid/images"

nc: 102

names:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - 'Metro'
  - 'A'
  - 'Bha'
  - 'Cha'
  - 'Chha'
  - 'Da'
  - 'DA'
  - 'E'
  - 'Ga'
  - 'Gha'
  - 'Ha'
  - 'Ja'
  - 'Jha'
  - 'Ka'
  - 'Kha'
  - 'La'
  - 'Ma'
  - 'Na'
  - 'Pa'
  - 'Sa'
  - 'Sha'
  - 'Ta'
  - 'THA'
  - 'Tha'
  - 'U'
  - 'Bagerhat'
  - 'Bagura'
  - 'Bandarban'
  - 'Barguna'
  - 'Barisal'
  - 'Bhola'
  - 'Brahmanbaria'
  - 'Chandpur'
  - 'Chapainawabganj'
  - 'Chatto'
  - 'Chattogram'
  - 'Chuadanga'
  - "Cox's Bazar"
  - 'Cumilla'
  - 'Dhaka'
  - 'Dinajpur'
  - 'Faridpur'
  - 'Feni'
  - 'Gaibandha'
  - 'Gazipur'
  - 'Gopalganj'
  - 'Habiganj'
  - 'Jamalpur'
  - 'Jessore'
  - 'Jhalokati'
  - 'Jhenaidah'
  - 'Joypurhat'
  - 'Khagrachari'
  - 'Khulna'
  - 'Kishoreganj'
  - 'Kurigram'
  - 'Kustia'
  - 'Lakshmipur'
  - 'Lalmonirhat'
  - 'Madaripur'
  - 'Magura'
  - 'Manikganj'
  - 'Meherpur'
  - 'Moulvibazar'
  - 'Mymensingh'
  - 'Naogaon'
  - 'Narail'
  - 'Narayanganj'
  - 'Narsingdi'
  - 'Natore'
  - 'Netrokona'
  - 'Nilphamari'
  - 'Noakhali'
  - 'Pabna'
  - 'panchagarh'
  - 'Patuakhali'
  - 'Pirojpur'
  - 'Raj'
  - 'Rajbari'
  - 'Rajshahi'
  - 'Rangamati'
  - 'Rangpur'
  - 'Satkhira'
  - 'Shariatpur'
  - 'Sherpur'
  - 'Sirajganj'
  - 'Sunamganj'
  - 'Sylhet'
  - 'Tangail'
  - 'Thakurgaon'
  - 'Dha'
  - 'Ba'
